### PR TITLE
Added identification for MAG274R series monitors.

### PR DESCRIPTION
**Pull request by wolfhechel**
Added the ID of MAG274R to the array of supported monitors. From the options that I've tested everything seems to be working. However, I have had some trouble with the connection occasionally dropping. It might be a hardware issue on my end though, I'll see what I can do about it, should it occur again.

### CODE REVIEW

**Comment by couriersud** [comment]
Would be great if you could post `msigd --debug --info --query` output as well.

**Comment by wolfhechel** [comment]
> Would be great if you could post `msigd --debug --info --query` output as well.

Sorry I don't have access to this monitor for a few months now, if I remember I'll post it when I'm back.

**Comment by wolfhechel** [comment]
Output from `msigd --debug --info --query`
```
EBUG: Initializing HID lib
DEBUG: Found <MSI Gaming Controller> with serial <A02019010700>
Vendor Id:      0x1462
Product Id:     0x3fa4
Product:        MSI Gaming Controller
Serial:         A02019010700
Monitor Series: MAG274R Series
LED support:    Mystic
s140:           <00Z>
s150:           <V41>
DEBUG: Special 01 b0: 01 5a 40 05 00 00 00 00 00 00 00 00 00 00 00 00
DEBUG: Special 01 b4: 01 5a 61 00 1b 42 00 00 00 00 00 00 00 00 00 00
DEBUG: Special 01 d0 62 30 30 31 30 30 30 30 30 0d: 01 d0 36 30 30 2b 0d 30 30 30 30 0d 00 00 00 00
macro_key : '000'
serial : '             '
frequency : '120'
game_mode : '000'
response_time : '002'
enable_dynamic : '000'
hdcr : '000'
refresh_display : '000'
refresh_position : '000'
alarm_clock : '000'
alarm_clock_index : '000'
alarm_clock_time : '00l'
alarm_position : '000'
screen_assistance : '000'
eye_saver : '000'
image_enhancement : '000'
brightness : '070'
contrast : '070'
sharpness : '000'
color_preset : '001'
color_red : '050'
color_green : '050'
color_blue : '050'
color_rgb : 'bbb'
osd_language : '001'
osd_transparency : '000'
osd_timeout : '020'
sound_enable : '001'
```

**Comment by wolfhechel** [comment]
This currently breaks with the recent changes to the codebase so don't merge it yet. I haven't figured out why but all settings that includes the entire MAG bitmask are missing after changing the bitmask of MAG274R to 0x00001000 (while incrementing all others accordingly).

**Comment by couriersud** [comment]
I have now added MAG274R to master.
It would be great if you could post the output of
```
./msigd --dump_mystic
```
and
```
msigd --debug --info --query
```
here.

**Comment by wolfhechel** [comment]
Sorry for the delayed response - yet again. Here's the dump:

```
Mystic record size: 168

0000: 72 21 ff 00 00 00 64 00
0008: ff 00 80 00 21 ff 00 00
0010: 00 64 00 ff 00 80 00 ff
0018: 00 00 ff 00 00 ff 00 00
0020: ff 00 00 ff 00 00 ff 00
0028: 00 ff 00 00 ff 00 00 ff
0030: 00 00 ff 00 00 ff 00 00
0038: ff 00 00 00 00 00 00 00
0040: 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00
0050: 00 00 00 00 00 00 00 00
0058: 00 00 00 00 00 00 00 ff
0060: 00 00 ff 00 00 ff 00 00
0068: ff 00 00 ff 00 00 ff 00
0070: 00 ff 00 00 ff 00 00 ff
0078: 00 00 ff 00 00 ff 00 00
0080: ff 00 00 00 00 00 00 00
0088: 00 00 00 00 00 00 00 00
0090: 00 00 00 00 00 00 00 00
0098: 00 00 00 00 00 00 00 00
00a0: 00 00 00 00 00 00 00 00
```

```
DEBUG: Initializing HID lib
DEBUG: Found <MSI Gaming Controller> with serial <A02019010700>
Vendor Id:      0x1462
Product Id:     0x3fa4
Product:        MSI Gaming Controller
Serial:         A02019010700
Monitor Series: MAG274R
LED support:    Mystic
s140:           <00Z>
s150:           <V41>
DEBUG: Special 01 b0: 01 5a 40 05 00 00 00 00 00 00 00 00 00 00 00 00
DEBUG: Special 01 b4: 01 5a 61 00 1b 42 00 00 00 00 00 00 00 00 00 00
DEBUG: Special 01 d0 62 30 30 31 30 30 30 30 30 0d: 01 d0 36 30 30 2b 0d 30 30 30 30 0d 00 00 00 00
macro_key : '000'
serial : '             '
frequency : '144'
game_mode : '000'
response_time : '002'
enable_dynamic : '000'
hdcr : '000'
refresh_display : '000'
refresh_position : '000'
alarm_clock : '000'
alarm_position : '000'
screen_assistance : '000'
free_sync : '000'
screen_size : '000'
night_vision : '001'
pro_mode : '000'
eye_saver : '000'
image_enhancement : '000'
brightness : '070'
contrast : '070'
sharpness : '000'
color_preset : '001'
color_red : '050'
color_green : '050'
color_blue : '050'
color_rgb : 'bbb'
input : '000'
auto_scan : '001'
osd_language : '001'
osd_transparency : '000'
osd_timeout : '020'
screen_info : '000'
sound_enable : '001'
rgb_led : '000'
power_button : '000'
navi_up : '001'
navi_down : '002'
navi_left : '001'
navi_right : '007'
```

**Comment by wolfhechel** [comment]
I've tried most commands and everything seems to be working perfectly fine for me. If that's all you can go ahead and close this PR, thanks for your work!

**Comment by couriersud** [comment]
Thanks a lot for the update. Fixed mystic support in master.

**Comment by wolfhechel** [comment]
Oh that's right, I didn't try out the mystic support since I have my RGB disabled and prefer to keep it that way.

**Pull request closed without merging**
